### ISSUE TITLE
ex8: Chart is not a constructor

### ISSUE THREAD

**Issue by moepmoep12** [SAP-samples/ui5-typescript-tutorial#8]
Hi,

I cannot run exercise 8 on a fresh install due to the error

`Uncaught (in promise) TypeError: Chart is not a constructor
    at _constructor._onAfterRendering [as onAfterRendering] (LineChart.ts:65:18)
    at Element._handleEvent (Element.js?eval:342:22)
    at finalizeRendering (RenderManager.js?eval:1275:16)
    at flushInternal (RenderManager.js?eval:1360:4)
    at RenderManager.render (RenderManager.js?eval:1510:4)
    at NavContainer.to (NavContainer.js:828:9)
    at TargetHandler._applyNavigationResult (TargetHandler.js:324:20)
    at TargetHandler.navigate (TargetHandler.js:100:32)
    at constructor.<anonymous> (Targets.js:36:26)`

Steps to reproduce:
- Clone repo
- Run `npm i` inside ex8
- Run `npm start`

When changing the default import to a named import `import { Chart } from "chart.js/auto";` a new error is thrown:

`Uncaught (in promise) Error: "line" is not a registered controller.
    at Registry._get (auto.js:6643:17)
    at Registry.getController (auto.js:6589:21)
    at Chart.buildOrUpdateControllers (auto.js:8294:46)
    at Chart.update (auto.js:8328:37)
    at Chart.<anonymous> (auto.js:8099:48)
    at Chart._doResize (auto.js:481:14)
    at Chart._resize (auto.js:8177:20)
    at Chart.resize (auto.js:8156:16)
    at attached (auto.js:8692:16)
    at Chart.bindResponsiveEvents (auto.js:8704:11)`

**Comment by akudev** [comment]
@moepmoep12: Chart.js changed incompatibly between 3.8.0 and 3.9.0: The default export was a class (constructor) in 3.8, but is a plain object in 3.9. And with the "^3.8.0" version setting in package.json it's now 3.9 what you get when you npm install from scratch.

The [release docs](https://github.com/chartjs/Chart.js/releases/tag/v3.9.0) don't mention this change.

Solution: you can fix the version in package.json to `"chart.js": "3.8.0",` and do `npm i` again.

We'll change the repo content accordingly.

**Comment by akudev** [comment]
3.8.0:
![image](https://user-images.githubusercontent.com/4866568/208869639-f782a214-7df8-425c-a09b-42996be14491.png)

3.9.0:
![image](https://user-images.githubusercontent.com/4866568/208869944-d2796d5e-e8a3-4115-a373-216054046752.png)

**Comment by akudev** [comment]
Tutorial is now updated. Thanks for reporting!

**Comment by Taking1998** [comment]
Hi,
I cannot run exercise 8 due to the error
![image](https://user-images.githubusercontent.com/66160588/228114862-0ad0242b-024f-4f89-a623-6adf044aed6e.png)
